<a href="https://colab.research.google.com/github/ayushd05/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys


In [ ]:
a= np.array([2,4,5,1])
print(a)

[2 4 5 1]


In [ ]:
a[0], a[1], a[-2]

(2, 4, 5)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
c=np.array([2,4,5,1], dtype= np.int8)
c.dtype

dtype('int8')

In [ ]:
A= np.array([
    [2,3,4],
    [5,3,1]
])

In [ ]:
#shape of the 2D array
A.shape

(2, 3)

In [ ]:
#Dimension of the array
A.ndim

2

In [ ]:
#Size of the array or the total numer the element in the array
A.size

6

In [ ]:
#Creating 3D Array
C= np.array([
    [
        [2,1,3,1],
        [1,2,5,7]
    ],
    [
        [3,12,87,12],
        [1,77,1,23]
    ]
])

In [ ]:
C.size

16

In [ ]:
C.ndim

3

In [ ]:
C.shape

(2, 2, 4)

In [ ]:
D=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)

In [ ]:
D.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

LINEAR ALGEBRA



In [ ]:
import numpy as np

A= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B=np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [ ]:
#for dot product
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
#for cross product
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
#FOR TRACE
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [ ]:
import sys
sys.getsizeof(1)

28

In [ ]:
words = ['Red', 'Yellow', 'Green' ]
for i in words :
    print(i, len(i))


Red 3
Yellow 6
Green 5


In [ ]:
import random
random.randint(0,99)

26

In [ ]:

import numpy as np
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a>=2

array([False, False,  True,  True])

SIZE OF OBJECTs IN PYTHON
