<a href="https://colab.research.google.com/github/ayushd05/python/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PANDAS


In [1]:
import pandas as pd
import numpy as np


In [2]:
g7_pop = pd.Series([12.212,21.323,546.534,234.234])

In [3]:
g7_pop


0     12.212
1     21.323
2    546.534
3    234.234
dtype: float64

In [4]:
g7_pop.name= "World health 4 countries"

In [5]:
g7_pop

0     12.212
1     21.323
2    546.534
3    234.234
Name: World health 4 countries, dtype: float64

In [6]:
g7_pop.dtype

dtype('float64')

In [7]:
g7_pop.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
g7_pop.index= [
    'ram',
    'shyam',
    'karan',
    'hero'
]

In [9]:
g7_pop

ram       12.212
shyam     21.323
karan    546.534
hero     234.234
Name: World health 4 countries, dtype: float64

In [10]:
#we can also give name, index and series at once
pd.Series(
    [12.21,332.12,23.232,12.3245],
    index=['ram', 'shyam', 'hero', 'manisha'],
    name='nothing so important'
)

ram         12.2100
shyam      332.1200
hero        23.2320
manisha     12.3245
Name: nothing so important, dtype: float64

In [11]:
#numeric postions can also be used, with the iloc attribute
g7_pop.iloc[0]
g7_pop.iloc[3]

234.234

In [12]:
g7_pop[['ram', 'shyam']]

ram      12.212
shyam    21.323
Name: World health 4 countries, dtype: float64

### DATA FRAMES

In [13]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'Population': [23,12,43],
    'Surface Area' : [21,32,42],
    'HDI' : [.12,
             .21,
             .54],
    'Continent': ['India', 'America', 'South-America']

}, columns= ['Population', 'Surface Area', 'HDI', "COntinent"])

In [14]:
import pandas as pd
import yfinance as yf
from datetime import datetime

start_date = datetime.now() - pd.DateOffset(months=3)
end_date = datetime.now()

tickers = ['AAPL', 'MSFT', 'NFLX', 'GOOG']

df_list = []

for ticker in tickers:
    data = yf.download(ticker, start=start_date, end=end_date)
    df_list.append(data)

df = pd.concat(df_list, keys=tickers, names=['Ticker', 'Date'])
print(df.head())

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
                         Open        High         Low       Close   Adj Close  \
Ticker Date                                                                     
AAPL   2023-06-20  184.410004  186.100006  184.410004  185.009995  184.760498   
       2023-06-21  184.899994  185.410004  182.589996  183.960007  183.711929   
       2023-06-22  183.740005  187.050003  183.669998  187.000000  186.747818   
       2023-06-23  185.550003  187.559998  185.009995  186.679993  186.428238   
       2023-06-26  186.830002  188.050003  185.229996  185.270004  185.020157   

                     Volume  
Ticker Date                  
AAPL   2023-06-20  49799100  
       2023-06-21  49515700  
       2023-06-22  51245300  
      

In [15]:
df = df.reset_index()
print(df.head())

  Ticker       Date        Open        High         Low       Close  \
0   AAPL 2023-06-20  184.410004  186.100006  184.410004  185.009995   
1   AAPL 2023-06-21  184.899994  185.410004  182.589996  183.960007   
2   AAPL 2023-06-22  183.740005  187.050003  183.669998  187.000000   
3   AAPL 2023-06-23  185.550003  187.559998  185.009995  186.679993   
4   AAPL 2023-06-26  186.830002  188.050003  185.229996  185.270004   

    Adj Close    Volume  
0  184.760498  49799100  
1  183.711929  49515700  
2  186.747818  51245300  
3  186.428238  53079300  
4  185.020157  48088700  


In [16]:
import plotly.express as px
fig = px.line(df, x='Date',
              y='Close',
              color='Ticker',
              title="Stock Market Performance for the Last 3 Months")
fig.show()

In [17]:
fig = px.area(df, x='Date', y='Close', color='Ticker',
              facet_col='Ticker',
              labels={'Date':'Date', 'Close':'Closing Price', 'Ticker':'Company'},
              title='Stock Prices for Apple, Microsoft, Netflix, and Google')
fig.show()

In [18]:
df['MA10'] = df.groupby('Ticker')['Close'].rolling(window=10).mean().reset_index(0, drop=True)
df['MA20'] = df.groupby('Ticker')['Close'].rolling(window=20).mean().reset_index(0, drop=True)

for ticker, group in df.groupby('Ticker'):
    print(f'Moving Averages for {ticker}')
    print(group[['MA10', 'MA20']])

Moving Averages for AAPL
          MA10        MA20
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN
..         ...         ...
59  182.320000  180.087500
60  181.129001  180.046000
61  179.843001  180.096500
62  178.694000  180.270499
63  177.640500  180.436749

[64 rows x 2 columns]
Moving Averages for GOOG
           MA10        MA20
192         NaN         NaN
193         NaN         NaN
194         NaN         NaN
195         NaN         NaN
196         NaN         NaN
..          ...         ...
251  136.787001  133.788501
252  136.993002  134.282501
253  137.088002  134.674501
254  137.304002  135.217001
255  137.497002  135.702502

[64 rows x 2 columns]
Moving Averages for MSFT
           MA10        MA20
64          NaN         NaN
65          NaN         NaN
66          NaN         NaN
67          NaN         NaN
68          NaN         NaN
..          ...         ...
123  332.159000  327.08

In [19]:
for ticker, group in df.groupby('Ticker'):
    fig = px.line(group, x='Date', y=['Close', 'MA10', 'MA20'],
                  title=f"{ticker} Moving Averages")
    fig.show()

In [20]:
df['Volatility'] = df.groupby('Ticker')['Close'].pct_change().rolling(window=10).std().reset_index(0, drop=True)
fig = px.line(df, x='Date', y='Volatility',
              color='Ticker',
              title='Volatility of All Companies')
fig.show()

In [21]:
import numpy as np

def list_to_3x3_array(digits):
    # Check if the input list has exactly 9 digits
    if len(digits) != 9:
        raise ValueError("Input list must contain exactly 9 digits.")

    # Reshape the list into a 3x3 NumPy array
    array_3x3 = np.array(digits).reshape(3, 3)

    return array_3x3

# Example usage:
input_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result_array = list_to_3x3_array(input_list)
print(result_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
